branches:
  except:
    - gh-pages

language: perl6

perl6:
  - latest
  - 2015.09

install:
  - rakudobrew build-panda ${TRAVIS_PERL6_VERSION#latest}
  - panda installdeps .
#  - rakudobrew build-panda 2015.09
  - panda update
  - panda install Digest::MD5 UUID


