branches:
  only:
    - master
#    - develop

language: perl6

perl6:
  - latest
#  - '2017.05'

install:
  - rakudobrew build zef
  - zef --depsonly --debug install .

#cache:
#  directories:
#    - $HOME/Travis-ci
#    - $HOME/.rakudobrew
