branches:
  only:
    - master

language: perl6

perl6:
  - latest

install:
  - rakudobrew build-panda ${TRAVIS_PERL6_VERSION#latest}
  - panda installdeps .
  - panda update
  - panda install Digest::MD5 UUID


