os: Visual Studio 2019

image:
  - Visual Studio 2019

platform: x64

branches:
  # whitelist
  only:
    - master
#    - develop

#install:
#  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
#  - choco feature enable -n allowEmptyChecksums
#  - choco install strawberryperl
#  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
#  - appveyor DownloadFile "http://rakudo.org/downloads/star/rakudo-star-latest-x86_64 (JIT).msi" -FileName "%APPVEYOR_BUILD_FOLDER%\rakudo.msi"
#  - msiexec /i rakudo.msi /quiet /qn /norestart /log install.log
#  - SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%
#  - zef --depsonly install .

install:
  - set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%

  # install raku from git
  - cd C:\
  - git clone https://github.com/rakudo/rakudo.git
  - cd rakudo
  - perl Configure.pl --gen-moar --gen-nqp --backends=moar
  - gmake install
  - set PATH=C:\rakudo\install\bin;C:\rakudo\install\share\perl6\site\bin;%PATH%
  - cmd: dir C:\rakudo\install\bin

  # install zef from git
  - cd C:\
  - git clone https://github.com/ugexe/zef.git
  - cd zef
  - cmd: rakudo.exe -I. bin/zef install .
  - cmd: dir C:\rakudo\install\share\perl6\site\bin

#  # set path to use MSYS2 tools like pacman
#  - cd C:\
#  - set PATH=C:\msys64\usr\bin;C:\msys64\usr\lib;%PATH%
#  - bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gtk3"

build: off

test_script:
#  - prove -v -e "perl6 -Ilib" t/
  # set path to use Raku, Zef and GTK libraries
  - set PATH=C:\rakudo\install\bin;C:\rakudo\install\share\perl6\site\bin;C:\msys64\mingw64\bin;%PATH%

  - cd %APPVEYOR_BUILD_FOLDER%
  - cmd: zef --/test --deps-only install .
  - cmd: zef --verbose install .

# fetch repository as zip archive
shallow_clone: true

# set clone depth
clone_depth: 4
